Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1,2]

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  MinSize: 5

Style/TernaryParentheses:
  Enabled: false

Style/WordArray:
  MinSize: 5
