module TheWizardsCastle
module Strings

  INTRO =<<END_INTRO
****************************************************************

               * * * THE WIZARD'S CASTLE * * *

****************************************************************

MANY CYCLES AGO, IN THE KINGDOM OF N'DIC, THE GNOMIC
WIZARD ZOT FORGED HIS GREAT *ORB OF POWER*. HE SOON
VANISHED, LEAVING BEHIND HIS VAST SUBTERRANEAN CASTLE
FILLED WITH ESURIENT MONSTERS, FABULOUS TREASURES, AND
THE INCREDIBLE *ORB OF ZOT*. FROM THAT TIME HENCE, MANY
A BOLD YOUTH HAS VENTURED INTO THE WIZARD'S CASTLE. AS
OF NOW, *NONE* HAS EVER EMERGED VICTORIOUSLY! BEWARE!!

END_INTRO
# Intro followed by pause

  CHARACTER_CREATION_HEADER = "ALL RIGHT, BOLD ONE."

  RACE_PROMPT = "YOU MAY BE AN ELF, DWARF, MAN, OR HOBBIT.\n\nYOUR CHOICE? "
  RACE_ERROR = "** THAT WAS INCORRECT. PLEASE TYPE E, D, M, OR H."

  GENDER_PROMPT = "WHICH SEX TO YOU PREFER? "
  def self.gender_error(race)
    "** CUTE #{race.to_s.upcase}, REAL CUTE. TRY M OR F."
  end

  def self.attributes_prompt_header(player,other_points)
    s =<<ATT_PROMPT_INTRO
OK, #{player.race.to_s.upcase}, YOU HAVE THE FOLLOWING ATTRIBUTES :
STRENGTH = #{player.str}  INTELLIGENCE = #{player.int}  DEXTERITY = #{player.dex}
AND #{other_points} OTHER POINTS TO ALLOCATE AS YOU WISH.
ATT_PROMPT_INTRO
  end

  STRENGTH_PROMPT = "HOW MANY POINTS DO YOU WISH TO ADD TO YOUR STRENGTH? "
  INTELLIGENCE_PROMPT = "HOW MANY POINTS DO YOU WISH TO ADD TO YOUR INTELLIGENCE? "
  DEXTERITY_PROMPT = "HOW MANY POINTS DO YOU WISH TO ADD TO YOUR DEXTERITY? "



end
end
