require 'the-wizards-castle/castle'
require 'the-wizards-castle/player'
require 'the-wizards-castle/printers/stetson_printer'
require 'the-wizards-castle/prompter'
require 'the-wizards-castle/room_content'
require 'the-wizards-castle/runner'
